/**
 * Injury Time domain types.
 *
 * This file is the single source of truth for the domain unions. The database
 * enforces the same sets with CHECK constraints (see
 * supabase/migrations/0001_core_schema.sql) — if you add a body region or a
 * status here, add it there in the same change, or the app will offer a value
 * the database rejects.
 */

export const POSITIONS = ['GK', 'DF', 'MF', 'FW'] as const
export type Position = (typeof POSITIONS)[number]

export const AVAILABILITY_STATUSES = ['fit', 'doubt', 'injured', 'suspended'] as const
export type AvailabilityStatus = (typeof AVAILABILITY_STATUSES)[number]

export const BODY_REGIONS = [
  'head',
  'neck',
  'shoulder',
  'arm',
  'wrist_hand',
  'chest',
  'back_upper',
  'back_lower',
  'hip',
  'groin',
  'quad',
  'hamstring',
  'knee',
  'calf',
  'shin',
  'achilles',
  'ankle',
  'foot',
] as const
export type BodyRegion = (typeof BODY_REGIONS)[number]

export const SIDES = ['left', 'right', 'central'] as const
export type Side = (typeof SIDES)[number]

export const SEVERITIES = ['knock', 'minor', 'moderate', 'severe'] as const
export type Severity = (typeof SEVERITIES)[number]

export const SESSION_KINDS = ['training', 'match'] as const
export type SessionKind = (typeof SESSION_KINDS)[number]

export const CLUB_ROLES = ['manager', 'physio'] as const
export type ClubRole = (typeof CLUB_ROLES)[number]

/** ISO date, `YYYY-MM-DD`. Postgres `date`, no time, no zone. */
export type DateString = string
/** ISO 8601 timestamp with offset. Postgres `timestamptz`. */
export type TimestampString = string

export type Club = {
  id: string
  name: string
  league: string
  is_demo: boolean
  created_at: TimestampString
}

export type ClubMember = {
  club_id: string
  user_id: string
  role: ClubRole
  created_at: TimestampString
}

export type Player = {
  id: string
  club_id: string
  name: string
  position: Position
  squad_number: number | null
  created_at: TimestampString
}

/**
 * Structured injury record. There is deliberately no free-text notes field:
 * Injury Time records what a manager needs to pick a side, and must not drift
 * into being a medical record.
 */
export type Injury = {
  id: string
  club_id: string
  player_id: string
  body_region: BodyRegion
  side: Side
  severity: Severity
  occurred_on: DateString
  expected_return: DateString | null
  resolved_on: DateString | null
  created_at: TimestampString
}

/** Append-only. A player's current state is the most recent row. */
export type AvailabilityEvent = {
  id: string
  club_id: string
  player_id: string
  status: AvailabilityStatus
  return_date: DateString | null
  injury_id: string | null
  noted_on: DateString
  created_at: TimestampString
}

export type Session = {
  id: string
  club_id: string
  session_date: DateString
  kind: SessionKind
  opponent: string | null
  minutes_planned: number | null
  created_at: TimestampString
}

/**
 * `load` is generated by the database as rpe * minutes; never write it.
 * Goals, assists and cards are only meaningful on a match session; a training
 * row keeps them at 0.
 */
export type SessionLoad = {
  id: string
  club_id: string
  session_id: string
  player_id: string
  rpe: number
  minutes: number
  load: number
  goals: number
  assists: number
  yellow: number
  red: number
  created_at: TimestampString
}

export const VENUES = ['H', 'A'] as const
export type Venue = (typeof VENUES)[number]

/** A match still to be played. Played matches become sessions. */
export type Fixture = {
  id: string
  club_id: string
  match_date: DateString
  kickoff: string | null
  opponent: string
  venue: Venue
  competition: string
  created_at: TimestampString
}

/** Row of the `current_availability` view: latest event per player. */
export type CurrentAvailability = {
  player_id: string
  club_id: string
  status: AvailabilityStatus
  return_date: DateString | null
  injury_id: string | null
  noted_on: DateString
}

type Generated = 'id' | 'created_at'

type Insertable<T, Optional extends keyof T = never> = Omit<T, Generated | Optional> &
  Partial<Pick<T, Extract<Generated | Optional, keyof T>>>

/**
 * Schema shape for the typed supabase-js client. Hand-written on purpose: it
 * stays readable, and it is the same file reviewers read for the domain unions.
 */
export type Database = {
  public: {
    Tables: {
      clubs: {
        Row: Club
        Insert: Insertable<Club, 'is_demo'>
        Update: Partial<Club>
        Relationships: []
      }
      club_members: {
        Row: ClubMember
        Insert: Omit<ClubMember, 'created_at'> & { created_at?: TimestampString }
        Update: Partial<ClubMember>
        Relationships: []
      }
      players: {
        Row: Player
        Insert: Insertable<Player, 'squad_number'>
        Update: Partial<Player>
        Relationships: []
      }
      injuries: {
        Row: Injury
        Insert: Insertable<Injury, 'expected_return' | 'resolved_on'>
        Update: Partial<Injury>
        Relationships: []
      }
      availability_events: {
        Row: AvailabilityEvent
        Insert: Insertable<AvailabilityEvent, 'return_date' | 'injury_id' | 'noted_on'>
        Update: Partial<AvailabilityEvent>
        Relationships: []
      }
      sessions: {
        Row: Session
        Insert: Insertable<Session, 'opponent' | 'minutes_planned'>
        Update: Partial<Session>
        Relationships: []
      }
      session_loads: {
        Row: SessionLoad
        // `load` is a generated column — the database computes it.
        Insert: Omit<SessionLoad, Generated | 'load' | 'goals' | 'assists' | 'yellow' | 'red'> &
          Partial<Pick<SessionLoad, 'goals' | 'assists' | 'yellow' | 'red'>> & {
            id?: string
            created_at?: TimestampString
          }
        Update: Partial<Omit<SessionLoad, 'load'>>
        Relationships: []
      }
      fixtures: {
        Row: Fixture
        Insert: Insertable<Fixture, 'kickoff'>
        Update: Partial<Fixture>
        Relationships: []
      }
    }
    Views: {
      current_availability: {
        Row: CurrentAvailability
        Relationships: []
      }
    }
    Functions: Record<never, never>
  }
}
