/**
 * Emits deterministic seed SQL for the demo club on stdout.
 * Storylines are engineered so the board demonstrates every state:
 * red spike (#10), current injury (#9), returner (#18), doubt (#5),
 * suspension (#7), undertraining watch (#13), steady ok (rest).
 */
import { DEMO_CLUB, FIXTURES, SQUAD, TRAINING_DAYS_AGO } from "./seed-data";

// mulberry32, fixed seed: reruns produce identical SQL
function rng(seed: number) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = rng(20260819);
const pick = (lo: number, hi: number) => lo + Math.floor(rand() * (hi - lo + 1));

const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/London" }).format(new Date());
function iso(daysAgo: number): string {
  const d = new Date(`${today}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() - daysAgo);
  return d.toISOString().slice(0, 10);
}
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const lines: string[] = [];
lines.push(`-- deterministic demo seed, generated by scripts/gen-seed-sql.ts`);
lines.push(`do $$`);
lines.push(`declare cid uuid; pid uuid; sid uuid; iid uuid;`);
lines.push(`  pids uuid[] := '{}'; -- by squad index`);
lines.push(`begin`);
lines.push(`select id into cid from public.clubs where is_demo and name = ${q(DEMO_CLUB.name)};`);
lines.push(`if cid is null then raise exception 'demo club missing'; end if;`);
lines.push(`delete from public.session_loads where club_id = cid;`);
lines.push(`delete from public.sessions where club_id = cid;`);
lines.push(`delete from public.availability_events where club_id = cid;`);
lines.push(`delete from public.injuries where club_id = cid;`);
lines.push(`delete from public.players where club_id = cid;`);

// players
for (const p of SQUAD) {
  lines.push(
    `insert into public.players (club_id, name, position, squad_number) values (cid, ${q(p.name)}, ${q(p.position)}, ${p.squadNumber}) returning id into pid; pids := pids || pid;`,
  );
}
const idx = (squadNumber: number) =>
  `pids[${SQUAD.findIndex((p) => p.squadNumber === squadNumber) + 1}]`;

// sessions + loads
type Sess = { daysAgo: number; kind: "training" | "match"; opponent?: string };
const sessions: Sess[] = [
  ...FIXTURES.map((f) => ({
    daysAgo: f.daysAgo,
    kind: "match" as const,
    opponent: `${f.opponent} (${f.venue}) · ${f.competition}`,
  })),
  ...TRAINING_DAYS_AGO.map((d) => ({ daysAgo: d, kind: "training" as const })),
].sort((a, b) => b.daysAgo - a.daysAgo);

// per-player narrative rules
const SPIKE = 10, INJURED = 9, RETURNER = 18, DOUBT = 5, SUSPENDED = 7, LOWLOAD = 13;
function entryFor(squadNumber: number, s: Sess): { rpe: number; minutes: number } | null {
  const isMatch = s.kind === "match";
  // Bobby (9): injured 2 days ago in the London Colney match - plays up to and including daysAgo 2, nothing after
  if (squadNumber === INJURED && s.daysAgo < 2) return null;
  // Emeka (18): out until 25 days ago (ankle), ramps back after
  if (squadNumber === RETURNER) {
    if (s.daysAgo > 25) return null;
    if (s.daysAgo > 14) return isMatch ? null : { rpe: pick(4, 5), minutes: pick(30, 45) };
    return isMatch ? { rpe: pick(8, 9), minutes: pick(60, 90) } : { rpe: pick(6, 7), minutes: pick(60, 75) };
  }
  // Kofi (7): sent off vs London Colney (daysAgo 2) - suspended, misses training since
  if (squadNumber === SUSPENDED && s.daysAgo < 2) return null;
  // Theo (10): the spike. Pre-spike he is MANAGED (capped 75min, steady
  // RPE) so his chronic base sits mid-pack; the last 10 days he plays
  // everything flat out. ACWR needs the low-then-high shape - a player
  // who is always maxed cannot red-flag on a ratio (found by T4 on the
  // live board: spiking only intensity lifted acute AND chronic, 1.17).
  if (squadNumber === SPIKE) {
    const hot = s.daysAgo <= 10;
    if (!hot) {
      return isMatch ? { rpe: 6, minutes: 55 } : { rpe: 6, minutes: 60 };
    }
    return isMatch ? { rpe: 9, minutes: 90 } : { rpe: 8, minutes: 85 };
  }
  // Tommy (13): backup GK - trains lightly, rarely plays
  if (squadNumber === LOWLOAD) {
    return isMatch ? null : { rpe: pick(3, 4), minutes: pick(40, 55) };
  }
  // GK #1 plays every match
  if (squadNumber === 1) {
    return isMatch ? { rpe: pick(5, 6), minutes: 90 } : { rpe: pick(4, 6), minutes: pick(55, 70) };
  }
  // everyone else: steady - matches 60-90min RPE 7-8, training RPE 5-7
  if (isMatch) {
    const started = rand() < 0.75;
    return started ? { rpe: pick(7, 8), minutes: 90 } : { rpe: pick(6, 7), minutes: pick(20, 45) };
  }
  const attended = rand() < 0.92;
  return attended ? { rpe: pick(5, 7), minutes: pick(60, 75) } : null;
}

for (const s of sessions) {
  lines.push(
    `insert into public.sessions (club_id, session_date, kind, opponent) values (cid, ${q(iso(s.daysAgo))}, ${q(s.kind)}, ${s.opponent ? q(s.opponent) : "null"}) returning id into sid;`,
  );
  const values: string[] = [];
  for (const p of SQUAD) {
    const e = entryFor(p.squadNumber, s);
    if (e) values.push(`(cid, sid, ${idx(p.squadNumber)}, ${e.rpe}, ${e.minutes})`);
  }
  if (values.length)
    lines.push(
      `insert into public.session_loads (club_id, session_id, player_id, rpe, minutes) values ${values.join(", ")};`,
    );
}

// injuries: current + season history for the body map
type Inj = { squad: number; region: string; side: string; severity: string; occurredAgo: number; resolvedAgo: number | null; expectedAgo?: number };
const injuries: Inj[] = [
  // current
  { squad: 9, region: "hamstring", side: "right", severity: "moderate", occurredAgo: 2, resolvedAgo: null, expectedAgo: -18 },
  { squad: 5, region: "knee", side: "left", severity: "knock", occurredAgo: 3, resolvedAgo: null, expectedAgo: -3 },
  // season history (resolved)
  { squad: 18, region: "ankle", side: "right", severity: "moderate", occurredAgo: 55, resolvedAgo: 25 },
  { squad: 10, region: "hamstring", side: "left", severity: "minor", occurredAgo: 240, resolvedAgo: 219 },
  { squad: 10, region: "calf", side: "left", severity: "knock", occurredAgo: 150, resolvedAgo: 143 },
  { squad: 4, region: "groin", side: "central", severity: "minor", occurredAgo: 190, resolvedAgo: 172 },
  { squad: 11, region: "back_lower", side: "central", severity: "minor", occurredAgo: 120, resolvedAgo: 108 },
  { squad: 2, region: "shoulder", side: "right", severity: "severe", occurredAgo: 290, resolvedAgo: 230 },
  { squad: 21, region: "quad", side: "right", severity: "minor", occurredAgo: 95, resolvedAgo: 84 },
  { squad: 17, region: "achilles", side: "left", severity: "knock", occurredAgo: 70, resolvedAgo: 64 },
];
for (const i of injuries) {
  lines.push(
    `insert into public.injuries (club_id, player_id, body_region, side, severity, occurred_on, expected_return, resolved_on) values (cid, ${idx(i.squad)}, ${q(i.region)}, ${q(i.side)}, ${q(i.severity)}, ${q(iso(i.occurredAgo))}, ${i.expectedAgo !== undefined ? q(iso(i.expectedAgo)) : "null"}, ${i.resolvedAgo !== null ? q(iso(i.resolvedAgo)) : "null"});`,
  );
}

// availability: baseline fit for all 45 days ago, then storyline events
for (const p of SQUAD) {
  lines.push(
    `insert into public.availability_events (club_id, player_id, status, noted_on) values (cid, ${idx(p.squadNumber)}, 'fit', ${q(iso(45))});`,
  );
}
// returner: injured 55d ago, fit again 25d ago
lines.push(`insert into public.availability_events (club_id, player_id, status, noted_on) values (cid, ${idx(18)}, 'injured', ${q(iso(55))});`);
lines.push(`insert into public.availability_events (club_id, player_id, status, noted_on) values (cid, ${idx(18)}, 'fit', ${q(iso(25))});`);
// current: Bobby injured (link latest injury), Liam doubt, Kofi suspended
lines.push(`select id into iid from public.injuries where player_id = ${idx(9)} and resolved_on is null limit 1;`);
lines.push(`insert into public.availability_events (club_id, player_id, status, return_date, injury_id, noted_on) values (cid, ${idx(9)}, 'injured', ${q(iso(-18))}, iid, ${q(iso(2))});`);
lines.push(`select id into iid from public.injuries where player_id = ${idx(5)} and resolved_on is null limit 1;`);
lines.push(`insert into public.availability_events (club_id, player_id, status, return_date, injury_id, noted_on) values (cid, ${idx(5)}, 'doubt', ${q(iso(-3))}, iid, ${q(iso(3))});`);
lines.push(`insert into public.availability_events (club_id, player_id, status, return_date, noted_on) values (cid, ${idx(7)}, 'suspended', ${q(iso(-11))}, ${q(iso(2))});`);
lines.push(`end $$;`);
console.log(lines.join("\n"));
