/**
 * Emits SQL for Belstone FC on stdout, from the committed season snapshot.
 *
 *   npx tsx scripts/seed-belstone.ts > belstone.sql && supabase db query --linked -f belstone.sql
 *
 * Belstone are a real club and these are real people, so the seed carries only
 * what the league publishes: the fixture list, results and scorers, the table,
 * the points line, and who has played how many games. No injuries, no
 * availability, no training sessions, no RPE: those get logged by the club.
 * Positions are unknown to the feed; every player is stored with
 * external_stats.position_confirmed = false so the board can ask for them.
 * Re-running replaces the club's season rows and players; it never duplicates.
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { fromSnapshot, matchPlayer, type Snapshot } from "../src/lib/league/normalise";

const snap = JSON.parse(readFileSync(resolve(__dirname, "belstone-2026-27.json"), "utf8")) as Snapshot;
const season = fromSnapshot(snap);
const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/London" }).format(new Date());
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const jsonb = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const nul = (v: number | string | null | undefined) => (v === null || v === undefined ? "null" : typeof v === "number" ? String(v) : q(v));

const lines: string[] = [];
lines.push(`-- belstone fc, ${snap.club.season}, from ${snap.club.source ?? "the league feed"}; generated by scripts/seed-belstone.ts`);
lines.push(`do $$`);
lines.push(`declare cid uuid; pid uuid;`);
lines.push(`begin`);
lines.push(`select id into cid from public.clubs where slug = ${q(snap.club.slug)};`);
lines.push(`if cid is null then`);
lines.push(
  `  insert into public.clubs (name, league, is_demo, slug, ground, division, season, founded, colours, settings) values (${q(snap.club.name)}, ${q(snap.club.league)}, true, ${q(snap.club.slug)}, ${nul(snap.club.ground ?? null)}, ${q(snap.club.division)}, ${q(snap.club.season)}, ${nul(snap.club.founded ?? null)}, ${jsonb({ home: "#000000", away: "#ffffff", accent: "#f5c518" })}, ${jsonb({ health_language: "plain" })}) returning id into cid;`,
);
lines.push(`else`);
lines.push(
  `  update public.clubs set name = ${q(snap.club.name)}, league = ${q(snap.club.league)}, is_demo = true, ground = ${nul(snap.club.ground ?? null)}, division = ${q(snap.club.division)}, season = ${q(snap.club.season)}, founded = ${nul(snap.club.founded ?? null)} where id = cid;`,
);
lines.push(`end if;`);

// the club's rows, cleared: everything hangs off players or the club id
for (const t of ["match_calls", "lineups", "clips", "notifications", "session_loads", "sessions", "availability_events", "injuries", "results", "league_standings", "league_progress", "fixtures", "players"]) {
  lines.push(`delete from public.${t} where club_id = cid;`);
}

// players: the appearance list, with the goals the feed attributes by surname
const goalsFor = (name: string): number | null => {
  const hit = season.goals.find((g) => matchPlayer(g.name, season.appearances.map((a) => ({ name: a.name })))?.name === name);
  return hit ? hit.goals : null;
};
for (const a of season.appearances) {
  const goals = goalsFor(a.name);
  const stats = { apps: a.apps, ...(goals !== null ? { goals } : {}), as_of: season.asOf, source: "snapshot", position_confirmed: false };
  lines.push(
    `insert into public.players (club_id, name, position, squad_number, external_stats) values (cid, ${q(a.name)}, 'MF', null, ${jsonb(stats)});`,
  );
}

// results
for (const r of season.results) {
  lines.push(
    `insert into public.results (club_id, match_date, competition, opponent, venue, goals_for, goals_against, ht_for, ht_against, attendance, scorers, source) values (cid, ${q(r.match_date)}, ${q(r.competition)}, ${q(r.opponent)}, ${q(r.venue)}, ${r.goals_for}, ${r.goals_against}, ${nul(r.ht_for)}, ${nul(r.ht_against)}, ${nul(r.attendance)}, array[${r.scorers.map(q).join(", ")}]::text[], 'snapshot');`,
  );
}

// still to play
for (const f of season.fixtures) {
  lines.push(
    `insert into public.fixtures (club_id, match_date, kickoff, opponent, venue, competition) values (cid, ${q(f.match_date)}, ${nul(f.kickoff)}, ${q(f.opponent)}, ${q(f.venue)}, ${q(f.competition)});`,
  );
}

// the table on the day it was read, and again as of today so "latest" is today
for (const asOf of [...new Set([season.asOf, today])]) {
  for (const s of season.standings) {
    lines.push(
      `insert into public.league_standings (club_id, as_of, position, team, played, won, drawn, lost, gf, ga, gd, points, home, away, is_us) values (cid, ${q(asOf)}, ${s.position}, ${q(s.team)}, ${s.played}, ${s.won}, ${s.drawn}, ${s.lost}, ${s.gf}, ${s.ga}, ${s.gd}, ${s.points}, ${jsonb(s.home)}, ${jsonb(s.away)}, ${s.is_us});`,
    );
  }
}

// points after each league match
for (const p of season.progress) {
  lines.push(`insert into public.league_progress (club_id, match_no, match_date, points, position) values (cid, ${p.match_no}, ${q(p.match_date)}, ${p.points}, ${nul(p.position)});`);
}

lines.push(`end $$;`);
console.log(lines.join("\n"));
